############################################
# SERVER
############################################
server.port=${PORT:8081}
server.url=http://localhost:${server.port}

############################################
# LOGGING
############################################
logging.level.org.atmosphere=warn


############################################
# SPRING PROFILE
############################################
spring.profiles.active=dev

############################################
# VAADIN CONFIGURATION
############################################
vaadin.launch-browser=true
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,dasturlash.uz

############################################
# CLIENT ID AND SECRET (Disabled for now)
############################################
# spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
# spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
# spring.security.oauth2.client.registration.google.scope=email,profile

